TDAT: public void set connection error ( sql exception e ) {  <NL> vector local = ( vector ) listeners . clone ( ) ;  <NL> for ( int i = local . size ( ) - 1 ; i > = 0 ; i - - ) {  <NL> try {  <NL>  ( ( connection event listener ) local . element at ( i ) )  <NL>  . connection error occurred ( new connection event ( this , e ) ) ;  <NL>  } catch ( runtime exception ex ) {  <NL>  / / there can be thrown an induced exception ,  <NL>  / / but we must report to client the original one , right ?  <NL> ex . print stack trace ( ) ;  <NL>  }  <NL>  }  <NL>  }  COM: <s> indicates that the connection given to the client has had an error </s>