TDAT: @ test public void test caller error ( ) throws throwable {  <NL> try {  <NL> this . init ( " test caller error " ) ;  <NL>  <NL> reset ( ) ;  <NL>  <NL> sip agent caller = create agent ( " caller " ) ;  <NL> sip agent callee = create agent ( " callee " ) ;  <NL>  <NL> make call ( ) ;  <NL> pause ( 1000 ) ;  <NL>  <NL> assert that ( caller , has ( recvd request ( " invite " ) ) ) ;  <NL> assert that ( callee , is ( idle ( ) ) ) ;  <NL>  <NL> caller . send response ( 180 ) ;  <NL> pause ( 1000 ) ;  <NL>  <NL> assert that ( callee , is ( idle ( ) ) ) ;  <NL>  <NL> caller . send response ( 480 ) ;  <NL> pause ( 1000 ) ;  <NL>  <NL> assert that ( callee , is ( idle ( ) ) ) ;  <NL> assert that ( caller , is ( disconnected ( ) ) ) ;  <NL> assert equals ( get state ( ) , " disconnected " ) ;  <NL>  }  <NL> catch ( throwable e ) {  <NL> logger . error ( " test failed " , e ) ;  <NL> throw e ;  <NL>  }  <NL>  }  COM: <s> test caller returning error </s>