TDAT: public void test callable statement parsing4 ( ) throws sql exception {  <NL> try {  <NL> con . prepare call ( " { call ? = sp _ create _ employee ( ? , ? , ? , ? , ? , ? ) } " ) ;  <NL> fail ( " was expecting an invalid escape sequence error " ) ;  <NL>  } catch ( sql exception ex ) {  <NL> assert equals ( " 22025 " , ex . get sql state ( ) ) ;  <NL>  }  <NL>  }  COM: <s> test for incorrect exception thrown no exception thrown when invalid </s>