TDAT: public void validate exhaustively ( ) throws data store exception {  <NL>  <NL>  <NL> try {  <NL> this . validate exhaustively worker ( this . get start constraint ( ) , this . get end constraint ( ) ) ;  <NL>  <NL>  }  <NL> catch ( seqdata exception sx ) {  <NL> log . log ( log . error , new throwable ( ) , sx ,  <NL> resource util . get message ( tdb assembly . class , " caught _ seqdata _ exception " ) ) ;  <NL>  <NL> string message = resource util . get resource ( tdb assembly . class , " text . caught _ seqdata _ exception " ,  <NL> sx . get message ( ) ) ;  <NL>  <NL> throw new data store exception ( message ) ;  <NL>  }  <NL>  <NL>  }  COM: <s> validate ourself exhaustively over our constrained range the </s>