TDAT: public void test09rdn name error ( ) {  <NL> map input = new hash map ( ) ;  <NL> input . put ( " nom " , " naquin " ) ;  <NL> input . put ( " pid " , " toto " ) ;  <NL> map lenv = new hash map ( ) ;  <NL> input . put ( " id " , " tutu " ) ;  <NL> npmock . reset ( ) ;  <NL> npmock . expects ( once ( ) ) . method ( " parse " ) . with ( eq ( " cn = tutu " ) ) . will (  <NL> throw exception ( new naming exception ( " invalid name " ) ) ) ;  <NL> npmock . expects ( once ( ) ) . method ( " parse " ) . with ( eq ( " cn = toto " ) ) . will (  <NL> return value ( cn ) ) ;  <NL> try {  <NL> sm . get input chain ( ) . add mapper ( new string variable ( " new rdn " , new variable string ( " cn = $ { id } " ) ) ) ;  <NL> sm . map ( input , lenv ) ;  <NL> fail ( " should have thrown exception " ) ;  <NL>  } catch ( mapper exception e ) {  <NL>  }  <NL>  }  COM: <s> error catching with rdn name </s>