TDAT: private void process terminating exception ( final throwable e ) {  <NL> e . print stack trace ( ) ;  <NL> try {  <NL> vm server . do callback ( new i callback runnable ( ) {  <NL> public object run ( i callback handler handler ) throws command exception {  <NL> return handler . callback with parms ( callback id , image data constants . image _ has _ exception , new object [ ] { e } ) ;  <NL>  }  <NL>  } ) ;  <NL>  } catch ( command exception e1 ) {  <NL> e1 . print stack trace ( ) ;  <NL>  }  <NL> image complete ( image data constants . image _ error ) ;  <NL>  }  COM: <s> terminating due to an exception </s>