TDAT: public void test bug20306 ( ) throws exception {  <NL> create table ( " test bug20306 " ,  <NL>  " ( field1 tinyint unsigned , field2 tinyint unsigned ) " ) ;  <NL> this . stmt . execute update ( " insert into test bug20306 values ( 2 , 133 ) " ) ;  <NL>  <NL> this . pstmt = this . conn <NL>  . prepare statement ( " select field1 , field2 from test bug20306 " ) ;  <NL> this . rs = this . pstmt . execute query ( ) ;  <NL> this . rs . next ( ) ;  <NL> check bug20306 ( ) ;  <NL>  <NL> this . rs = this . stmt <NL>  . execute query ( " select field1 , field2 from test bug20306 " ) ;  <NL> this . rs . next ( ) ;  <NL> check bug20306 ( ) ;  <NL>  <NL>  }  COM: <s> tests fix for bug 20306 result set </s>