TDAT: public void test read ( ) throws exception {  <NL> report line collector colly = new report line collector ( is ) ;  <NL>  <NL>  / / wait for collection to complete <NL> colly . inner thread . join ( 2000 ) ;  <NL>  <NL> my piped input stream izzy = new my piped input stream ( ) ;  <NL> colly . in pipe = izzy ;  <NL>  <NL> assert true ( " read already called on izzy " , ! izzy . read called ) ;  <NL> assert equals ( " wrong val returned " , - 41 , colly . read ( ) ) ;  <NL> assert true ( " read not called on izzy " , izzy . read called ) ;  <NL>  }  COM: <s> see that read correctly reads from the internal pipe </s>