TDAT: public void delete ( int id ) throws sql exception {  <NL>  <NL>  / / todo : we should not allow this delete if there are incidents out <NL>  / / there - or maybe we should , and archive the incidents ? i dunno <NL>  <NL>  / / sanity check - if id is null there ' s nothing to do <NL> if ( id = = - 1 ) {  <NL> return ;  <NL>  }  <NL>  <NL> try {  <NL> this . conn = this . open connection ( ) ;  <NL>  <NL> prepared statement ps =  <NL> conn . prepare statement ( product sql . delete _ product ) ;  <NL> ps . set int ( 1 , id ) ;  <NL> ps . execute update ( ) ;  <NL>  } finally {  <NL> this . close connection ( ) ;  <NL>  }  <NL>  }  COM: <s> used to remove a product from the product table </s>