TDAT: public void test rollback on escalation ( ) throws throwable {  <NL>  <NL> final sql exception exception = new sql exception ( " test " ) ;  <NL>  <NL>  / / record transaction steps <NL> this . object . begin ( ) ;  <NL> this . object . step one ( ) ;  <NL> this . control ( this . object ) . set throwable ( exception ) ;  <NL> this . object . rollback ( ) ;  <NL>  <NL>  / / configure tasks <NL> this . construct raw tasks ( ) ;  <NL>  <NL>  / / test <NL> try {  <NL> this . do test ( false ) ;  <NL> fail ( " should not be successful " ) ;  <NL>  } catch ( sql exception ex ) {  <NL> assert same ( " incorrect exception " , exception , ex ) ;  <NL>  }  <NL>  }  COM: <s> ensure rollback on </s>