TDAT: public void test _ shutdown _ interrupted ( ) throws interrupted exception {  <NL>  <NL> final mock transaction service service = new fixture ( ) ;  <NL>  <NL> try {  <NL>  <NL>  / / final long tx =  <NL> service . new tx ( i tx . unisolated ) ;  <NL>  <NL> final thread t = new thread ( ) {  <NL>  <NL> public void run ( ) {  <NL>  <NL> service . shutdown ( ) ;  <NL>  <NL>  }  <NL>  <NL>  } ;  <NL>  <NL> t . set daemon ( true ) ;  <NL>  <NL> t . start ( ) ;  <NL>  <NL> service . await run state ( tx service run state . shutdown ) ;  <NL>  <NL>  / / interrupt the thread running shutdown ( ) .  <NL> t . interrupt ( ) ;  <NL>  <NL> service . await run state ( tx service run state . halted ) ;  <NL>  <NL>  } finally {  <NL>  <NL> service . destroy ( ) ;  <NL>  <NL>  }  <NL>  <NL>  }  COM: <s> test that shutdown may be interrupted while waiting for a tx to </s>