TDAT: public void test03 _ invoke after application exception ( ) {  <NL> try {  <NL> string expected = " success " ;  <NL> string actual = ejb object . business method ( " sseccu s " ) ;  <NL> assert equals ( expected , actual ) ;  <NL>  } catch ( throwable e ) {  <NL> fail ( " received exception " + e . get class ( ) + " : " + e . get message ( ) ) ;  <NL>  }  <NL>  }  COM: <s> after an application exception we should still be able to </s>