TDAT: private void do delete ( uri resource ) throws exception {  <NL>  / / does the resource even exist ?  <NL> closable iterator < triple > iter = null ;  <NL> try {  <NL>  / / haqq ! - cannot read and delete from same store concurrently !  <NL> set < triple > statements = new hash set < triple > ( ) ;  <NL> iter = helper . get resource ( resource , this . data ) ;  <NL> while ( iter . has next ( ) ) {  <NL> statements . add ( iter . next ( ) ) ;  <NL>  }  <NL> this . data . remove ( statements . iterator ( ) ) ;  <NL>  <NL>  / / iter = helper . get resource ( resource , this . data ) ;  <NL>  / / this . data . remove ( iter ) ;  <NL>  } finally {  <NL> iter . close ( ) ;  <NL>  }  <NL>  }  COM: <s> performs the delete operation </s>